fragment CartFrag on Cart {
    id
    checkoutUrl
    cost {
      subtotalAmount {
        amount
      }
    }
    lines(first: 10) {
      edges {
        node {
          id
          quantity
          cost {
            amountPerQuantity {
              amount
            }
            subtotalAmount {
              amount
            }
          }
          merchandise {
            ... on ProductVariant {
              id
              title
              product {
                id
                title
                handle
                featuredImage {
                  width
                  height
                  altText
                  url
                }
              }
            }
          }
        }
      }
    }
}