query productsByCollections($query: String!) {
  collections(first: 10, query: $query) {
    nodes {
      description
      title
      handle
      id
      products(first: 10) {
        nodes {
          title
          short_description: metafield(key: "short_description", namespace: "custom") {
            id
            value
          }
          handle
          id
          featuredImage {
            altText
            height
            id
            url
            width
          }
          priceRange {
            minVariantPrice {
              amount
            }
          }
          variants(first: 10) {
            nodes {
              id
              price {
                amount
              }
              title
            }
          }
        }
      }
    }
  }
}